# Generated by Django 5.2.13 on 2026-04-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='correo',
            new_name='correo_electronico',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='documento',
            new_name='documento_de_identidad',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='fecha',
            new_name='fecha_de_asistencia',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='hora_ingreso',
            new_name='hora_de_ingreso',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='hora_salida',
            new_name='hora_de_salida',
        ),
    ]
