# Generated by Django 6.0.4 on 2026-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='descripcion_detallada',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='documento_identidad',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_solicitud',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='nombre_solicitante',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='telefono_contacto',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_solicitud',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/', verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='correo',
            field=models.EmailField(default='test@test.com', max_length=254, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='descripcion',
            field=models.TextField(default='Sin descripción', verbose_name='Descripción detallada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='documento',
            field=models.CharField(default='123456789', max_length=50, verbose_name='Documento de identidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateField(default='2024-01-01', verbose_name='Fecha de la solicitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(default='Juan Perez', max_length=150, verbose_name='Nombre del solicitante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(default='3001234567', max_length=20, verbose_name='Teléfono de contacto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], default='academica', max_length=20, verbose_name='Tipo de solicitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='asunto',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
    ]
